POST http://localhost:8080/api/v1/job
Content-Type: application/json

{
    "name": "testing",
    "tasks": [
        {
            "name": "hallo-world",
            "image": "debian:latest",
            "depends": [],
            "cmd": [
                "sh",
                "-c",
                "echo $MESSAGE  >> /task-output-foo.txt"
            ],
            "env": [
                {
                    "name": "MESSAGE",
                    "value": "Hallo world"
                }
            ],
            "outputs": [
                {
                    "name": "foo-output",
                    "path": "/task-output-foo.txt"
                }
            ]
        },
        {
            "name": "replace-letter-a",
            "image": "debian:latest",
            "depends": [
                "hallo-world"
            ],
            "cmd": [
                "sh",
                "-c",
                "cat /task-input.txt | sed 's/a/e/g' > /task-output-replace-letter-a.txt"
            ],
            "env": [],
            "inputs": [
                {
                    "from": "foo-output",
                    "path": "/task-input.txt"
                }
            ],
            "outputs": [
                {
                    "name": "replace-letter-a-output",
                    "path": "/task-output-replace-letter-a.txt"
                }
            ]
        }
    ]
}

###

GET http://localhost:8080/api/v1/job/59

###

GET http://localhost:8080/api/v1/job

###

GET http://localhost:8080/api/v1/artefact/21/replace-letter-a-output

###

POST http://localhost:8080/api/v1/secret/test-key
Content-Type: application/json

"test-value"

###

DELETE http://localhost:8080/api/v1/secret/test-key

###

PUT http://localhost:8080/api/v1/secret/test-key
Content-Type: application/json

"new-test-value"

###

GET ws://localhost:8080/api/v1/scheduler/ws