apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    metadata:
      name: test-job
    spec:
      containers:
        - name: test-job
          image: alpine:3.14
          command: ["sleep", "5"]
      restartPolicy: Never
