apiVersion: v1
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: "2023-01-07T09:17:21Z"
      generateName: test-job-
      labels:
        controller-uid: 456ffe5b-5fbe-4955-8c1a-39466917c318
        job-name: test-job
      name: test-job-mr7d6
      namespace: default
      ownerReferences:
        - apiVersion: batch/v1
          blockOwnerDeletion: true
          controller: true
          kind: Job
          name: test-job
          uid: 456ffe5b-5fbe-4955-8c1a-39466917c318
      resourceVersion: "1456"
      uid: 81bac626-2b54-4a75-9668-fa7d569ef740
    spec:
      containers:
        - command:
            - sleep
            - "5"
          image: alpine:3.14
          imagePullPolicy: IfNotPresent
          name: test-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-fqqkz
              readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      imagePullSecrets:
        - name: ghcr-login-secret
      nodeName: k3d-flowmium-playground-server-0
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - name: kube-api-access-fqqkz
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
    status:
      conditions:
        - lastProbeTime: null
          lastTransitionTime: "2023-01-07T09:17:21Z"
          reason: PodCompleted
          status: "True"
          type: Initialized
        - lastProbeTime: null
          lastTransitionTime: "2023-01-07T09:17:26Z"
          reason: PodCompleted
          status: "False"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: "2023-01-07T09:17:26Z"
          reason: PodCompleted
          status: "False"
          type: ContainersReady
        - lastProbeTime: null
          lastTransitionTime: "2023-01-07T09:17:21Z"
          status: "True"
          type: PodScheduled
      containerStatuses:
        - containerID: containerd://2665b2923238d2983fb78cd1cb32bfa7a13b8b67eb87a228dfdc81233a1e9dd7
          image: docker.io/library/alpine:3.14
          imageID: docker.io/library/alpine@sha256:4c869a63e1b7c0722fed1e402a6466610327c3b83bdddb94bd94fb71da7f638a
          lastState: {}
          name: test-job
          ready: false
          restartCount: 0
          started: false
          state:
            terminated:
              containerID: containerd://2665b2923238d2983fb78cd1cb32bfa7a13b8b67eb87a228dfdc81233a1e9dd7
              exitCode: 0
              finishedAt: "2023-01-07T09:17:26Z"
              reason: Completed
              startedAt: "2023-01-07T09:17:21Z"
      hostIP: 172.18.0.3
      phase: Succeeded
      podIP: 10.42.0.17
      podIPs:
        - ip: 10.42.0.17
      qosClass: BestEffort
      startTime: "2023-01-07T09:17:21Z"
kind: List
metadata:
  resourceVersion: ""
