name: Code formatting, semantic checking and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_review:
    types:
      - submitted

jobs:
  rust-check:
    name: Checks for Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Check formatting
        run: cargo fmt --check
        working-directory: flowmium
      - name: Start test services
        run: docker-compose -f test-services.yaml up -d
        working-directory: flowmium
      - name: Wait for test services to be healthy
        timeout-minutes: 5
        run: |
          for cid in $(docker ps -a -q); do
            while [ "`docker inspect -f {{.State.Status}} $cid`" != "running" ]; do
              sleep 2;
            done
          done
      - name: Install sqlx CLI
        run: cargo install sqlx-cli
        working-directory: flowmium
      - name: Run migrations on test database
        run: sqlx migrate run
        working-directory: flowmium
      - name: Run clippy
        run: cargo clippy
        working-directory: flowmium
      - name: Run tests
        run:  FLOWMIUM_INIT_CONTAINER_IMAGE_FROM_SOURCE=true make test
        working-directory: flowmium
  python-check:
    name: Checks for Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry
        working-directory: framework
      - name: Install dependencies
        run: poetry install
        working-directory: framework
      - name: Check formatting
        run: poetry run black . --check
        working-directory: framework
      - name: Run flake8
        run: poetry run flake8 flowmium tests
        working-directory: framework
      - name: Run mypy
        run: poetry run mypy flowmium tests
        working-directory: framework
      - name: Run pytest
        run: poetry run pytest
        working-directory: framework
